# Start1

## Tensor是什么？
Tensor是一个概念在数学和计算机科学中的术语，它表示多维数组或张量。在机器学习中，张量是用来表示多维数据的常见数据结构。TensorFlow是一个开源的机器学习框架，它采用了张量作为其主要的数据表示方式，并支持在大规模分布式计算环境中进行高效的数值计算。

张量可以被视作一种扩展的矩阵，可以具有任意数量的维度。例如，一个一维的张量是一个向量，二维的张量是一个矩阵，而三维或更高维的张量可以表示更复杂的数据结构，比如图像或视频。

在TensorFlow中，张量是数据的核心表示形式。它们可以存储在计算图的节点中，并作为输入或输出传递给不同的操作。张量可以具有不同的数据类型，比如浮点数、整数或布尔值，以及不同的形状，即每个维度的大小。

使用张量作为数据的表示形式使得TensorFlow能够执行高效的数值计算，并在复杂的模型和大规模数据集上进行训练和推理。通过定义计算图和使用张量操作，开发者可以利用TensorFlow的强大功能来构建和训练各种机器学习模型。

## 标量



In [2]:
import os
print(os.path.abspath('.'))

D:\code\Ai_starter\directory1


In [7]:
import numpy as np
array = np.array([1,2,3,4,5])
array2 = array + 1
print(array2)

[2 3 4 5 6]


In [12]:
array2+array
print(array2+array)
array2*array

[ 3  5  7  9 11]


array([ 2,  6, 12, 20, 30])

In [17]:
print(array.ndim)
print(array.shape)

1
(5,)


In [19]:
list = [3,4,5,6,7]
list.shape

AttributeError: 'list' object has no attribute 'shape'

In [29]:
array3 = np.array(list)
array3.shape
type(array3)
array3.dtype

dtype('int32')

In [33]:
print(array3.shape)
print(array3.size)

(5,)
5


In [36]:
array3[1:3]

array([4, 5])

In [39]:
array4=np.array([[1,2,3],[4,5,6],[7,8,9]])
array4[1,1] = 100
print(array4)
array4[1]

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


array([  4, 100,   6])

In [53]:
mask = np.array([11,1,1,0,0,-1,1,0,0,1],dtype=bool)
print(mask)

[ True  True  True False False  True  True False False  True]


In [55]:
array = np.arange(0,100,10)
print(array)
array[mask]

[ 0 10 20 30 40 50 60 70 80 90]


array([ 0, 10, 20, 50, 60, 90])

In [59]:
array = np.random.rand(10)
print(array)
mask = array>0.5
print(array[mask])

[0.6000459  0.36494855 0.24826247 0.06970919 0.80096416 0.14246215
 0.24395416 0.30183497 0.4351986  0.11551882]
[0.6000459  0.80096416]


In [61]:
print(help(np.loadtxt))

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)
    Load data from a text file.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return bytes or strings. The strings
        in a list or produced by a generator are treated as lines.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type